# Generated by Django 5.2.6 on 2025-10-24 13:37

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hotel_name', models.CharField(max_length=40, unique=True)),
                ('hotel_address', models.CharField(max_length=60)),
                ('hotel_star', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('hotel_contact', models.CharField(blank=True, max_length=30)),
                ('hotel_email', models.EmailField(blank=True, max_length=254)),
                ('hotel_about', models.TextField(blank=True)),
                ('hotel_image', models.ImageField(blank=True, default='hotel_def.jpg', null=True, upload_to='hotel_photos')),
            ],
            options={
                'verbose_name_plural': 'Hotels',
                'db_table': 'Hotels',
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_type', models.CharField(max_length=30)),
                ('room_number', models.PositiveIntegerField()),
                ('room_price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('room_available', models.BooleanField(default=True)),
                ('room_image', models.ImageField(blank=True, default='room_def.jpg', null=True, upload_to='room_photos')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='hotel_app.hotel')),
            ],
            options={
                'verbose_name_plural': 'Rooms',
                'db_table': 'Rooms',
                'unique_together': {('hotel', 'room_number')},
            },
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guests', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(3)])),
                ('check_in', models.DateField()),
                ('check_out', models.DateField()),
                ('total_price', models.DecimalField(decimal_places=2, editable=False, max_digits=10)),
                ('status', models.CharField(choices=[('active', 'active'), ('completed', 'completed'), ('canceled', 'canceled')], default='active', max_length=30)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='hotel_app.hotel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to=settings.AUTH_USER_MODEL)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='hotel_app.room')),
            ],
            options={
                'verbose_name_plural': 'Reservations',
                'db_table': 'Reservations',
                'ordering': ['check_in'],
            },
        ),
        migrations.CreateModel(
            name='RoomImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(upload_to='room_carusel')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_carusel', to='hotel_app.room')),
            ],
        ),
    ]
