# Generated by Django 5.2.6 on 2025-10-26 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_app', '0002_hotelsimages'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hotel',
            options={'ordering': ['hotel_name'], 'verbose_name_plural': 'Hotels'},
        ),
        migrations.AlterModelOptions(
            name='room',
            options={'ordering': ['hotel', 'room_number'], 'verbose_name_plural': 'Rooms'},
        ),
        migrations.AlterField(
            model_name='reservation',
            name='status',
            field=models.CharField(choices=[('active', 'active'), ('completed', 'completed'), ('canceled', 'canceled'), ('upcoming', 'upcoming')], default='active', max_length=30),
        ),
    ]
